### ISSUE TITLE
Exporter OOMKilled

### ISSUE THREAD

**Issue by rodgar-nvkz** [PrefectHQ/prometheus-prefect-exporter#44]
### Describe the bug a clear and concise description of what the bug is.

After update from Chart 2024.8.15191644 (code release 1.4.0) to Chart 2024.9.3172343 (code release 1.5.0) collector pod having being killed by OOM reason even before its getting fully initialised.

### Application name

prometheus-prefect-exporter

### Application version

1.5.0

### Explain bug

After new release pagination was added.
PrefectFlowRuns.get_all_flow_runs_info() query all flows from the server without any filtering.
All together it leads to all flow runs for entire history being loaded from the server.

### What you expected to happen?

Exporter do not downloading all flow runs history from the server

### How to reproduce it?

Run exporter connected to a prefect server with 100K finished flows

**Comment by sfai05** [comment]
I'm experiencing similar issues after upgrading to version 1.5.0:

1. **Increased RAM Usage:**
   - Before: ~100MB
   - After: 1Gi (10x increase)

2. **/metrics Endpoint:**
   - Responding very slowly
   - Consistently timing out when Prometheus pulls data

3. **Environment:**
   - Prefect server: v2.14.17
   - ~200 flow runs per day

Due to these issues, we've reverted to version 1.4.0 as a temporary solution.

Happy to provide more details if needed.

**Comment by mitchnielsen** [comment]
Thank you both for the report. We'll take a look at this as soon as possible. In the meantime, `1.4.0` can be used as `@sfai05` recommended.

**Comment by jimid27** [comment]
👋 We have updated the exporter to allow for enabling or disabling pagination along w/ setting your own pagination limits.  If you have installed the exporter via helm you can update the chart version and disable pagination through the helm values found [here](https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prometheus-prefect-exporter/values.yaml#L39).  If you have deployed manually you can bump the image version disable pagination by setting the environment variable PAGINATION_ENABLED to False.  Let us know if you have any issues!
